/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0c0e10",
        "outline": "#a78b7d",
        "on-secondary": "#003915",
        "tertiary-fixed": "#c4e7ff",
        "primary-fixed": "#ffdbca",
        "on-secondary-fixed-variant": "#005321",
        "error-container": "#93000a",
        "on-primary": "#552100",
        "background": "#121416",
        "on-tertiary-container": "#00374d",
        "on-secondary-container": "#004119",
        "on-primary-fixed-variant": "#783200",
        "surface": "#121416",
        "secondary-fixed": "#6bff8f",
        "surface-variant": "#333537",
        "on-background": "#e2e2e5",
        "inverse-on-surface": "#2f3133",
        "on-tertiary-fixed-variant": "#004c69",
        "on-tertiary": "#00354a",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001e2c",
        "surface-container": "#1e2022",
        "primary": "#ffb690",
        "on-primary-fixed": "#341100",
        "primary-container": "#f97316",
        "surface-tint": "#ffb690",
        "secondary": "#4ae176",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4ae176",
        "surface-dim": "#121416",
        "tertiary-container": "#00a6df",
        "surface-bright": "#38393c",
        "outline-variant": "#584237",
        "primary-fixed-dim": "#ffb690",
        "on-surface": "#e2e2e5",
        "surface-container-highest": "#333537",
        "surface-container-low": "#1a1c1e",
        "inverse-primary": "#9d4300",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-surface-variant": "#e0c0b1",
        "on-secondary-fixed": "#002109",
        "surface-container-high": "#282a2c",
        "inverse-surface": "#e2e2e5",
        "tertiary": "#7bd0ff",
        "secondary-container": "#00b954",
        "on-primary-container": "#582200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "label-lg": ["'Inter'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
        "mono-metric": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { fontWeight: "800", letterSpacing: "-0.02em", lineHeight: "48px" }],
        "display-lg-mobile": ["30px", { fontWeight: "800", letterSpacing: "-0.01em", lineHeight: "36px" }],
        "headline-xl": ["28px", { fontWeight: "700", letterSpacing: "-0.02em", lineHeight: "36px" }],
        "headline-lg": ["22px", { fontWeight: "700", letterSpacing: "-0.01em", lineHeight: "28px" }],
        "headline-md": ["18px", { fontWeight: "600", lineHeight: "24px" }],
        "body-lg": ["16px", { fontWeight: "400", lineHeight: "24px" }],
        "body-md": ["14px", { fontWeight: "400", lineHeight: "20px" }],
        "body-sm": ["12px", { fontWeight: "400", lineHeight: "16px" }],
        "label-lg": ["14px", { fontWeight: "600", letterSpacing: "0.01em", lineHeight: "20px" }],
        "label-md": ["12px", { fontWeight: "700", letterSpacing: "0.04em", lineHeight: "16px" }],
        "label-sm": ["10px", { fontWeight: "700", letterSpacing: "0.06em", lineHeight: "12px" }],
        "mono-metric": ["15px", { fontWeight: "600", letterSpacing: "0.02em", lineHeight: "20px" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-mobile": "0.5rem",
        margin: "1.5rem",
        "margin-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
    },
  },
  plugins: [],
};
