/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "outline": "#cbd5e1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e0f2fe",
        "primary-fixed": "#ffedd5",
        "on-secondary-fixed-variant": "#047857",
        "error-container": "#fee2e2",
        "on-primary": "#ffffff",
        "background": "#f8fafc",
        "on-tertiary-container": "#0369a1",
        "on-secondary-container": "#065f46",
        "on-primary-fixed-variant": "#9a3412",
        "surface": "#ffffff",
        "secondary-fixed": "#a7f3d0",
        "surface-variant": "#e2e8f0",
        "on-background": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "on-tertiary-fixed-variant": "#0284c7",
        "on-tertiary": "#ffffff",
        "error": "#dc2626",
        "on-error-container": "#991b1b",
        "on-tertiary-fixed": "#0c4a6e",
        "surface-container": "#f1f5f9",
        "primary": "#ea580c",
        "on-primary-fixed": "#7c2d12",
        "primary-container": "#f97316",
        "surface-tint": "#ea580c",
        "secondary": "#059669",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#6ee7b7",
        "surface-dim": "#e2e8f0",
        "tertiary-container": "#e0f2fe",
        "surface-bright": "#ffffff",
        "outline-variant": "#e2e8f0",
        "primary-fixed-dim": "#fed7aa",
        "on-surface": "#0f172a",
        "surface-container-highest": "#cbd5e1",
        "surface-container-low": "#f8fafc",
        "inverse-primary": "#ffedd5",
        "tertiary-fixed-dim": "#7dd3fc",
        "on-surface-variant": "#475569",
        "on-secondary-fixed": "#064e3b",
        "surface-container-high": "#e2e8f0",
        "inverse-surface": "#0f172a",
        "tertiary": "#0284c7",
        "secondary-container": "#d1fae5",
        "on-primary-container": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "label-lg": ["'Inter'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
        "mono-metric": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { fontWeight: "800", letterSpacing: "-0.02em", lineHeight: "48px" }],
        "display-lg-mobile": ["30px", { fontWeight: "800", letterSpacing: "-0.01em", lineHeight: "36px" }],
        "headline-xl": ["28px", { fontWeight: "700", letterSpacing: "-0.02em", lineHeight: "36px" }],
        "headline-lg": ["22px", { fontWeight: "700", letterSpacing: "-0.01em", lineHeight: "28px" }],
        "headline-md": ["18px", { fontWeight: "600", lineHeight: "24px" }],
        "body-lg": ["16px", { fontWeight: "400", lineHeight: "24px" }],
        "body-md": ["14px", { fontWeight: "400", lineHeight: "20px" }],
        "body-sm": ["12px", { fontWeight: "400", lineHeight: "16px" }],
        "label-lg": ["14px", { fontWeight: "600", letterSpacing: "0.01em", lineHeight: "20px" }],
        "label-md": ["12px", { fontWeight: "700", letterSpacing: "0.04em", lineHeight: "16px" }],
        "label-sm": ["10px", { fontWeight: "700", letterSpacing: "0.06em", lineHeight: "12px" }],
        "mono-metric": ["15px", { fontWeight: "600", letterSpacing: "0.02em", lineHeight: "20px" }],
      },
      spacing: {
        gutter: "1rem",
        "gutter-mobile": "0.5rem",
        margin: "1.5rem",
        "margin-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
    },
  },
  plugins: [],
};
